D-Programming-Deimos/openssl

deimos/openssl/ec.d
please pay attention to this simple one-letter patch
without patch usage of this function causes:
../.dub/packages/openssl-1.1.3_1.0.1g/deimos/openssl/ec.d(955): Error: undefined identifier EVP_PKEX_CTX, did you mean alias EVP_PKEY_CTX?
=> typo in ec.d

deimos/openssl/crypto.d
calling e.g. OPENSSL_malloc(16);
doesn't compile (actually DMD64 D Compiler v2.077.1, though it doesn't matter here):
../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/crypto.d(371,22): Error: function deimos.openssl.crypto.CRYPTO_malloc (int num, const(char)* file, int line) is not callable using argument types (int, string, ulong)
source/acos5_64.d(2423,15): Error: template instance deimos.openssl.crypto.OPENSSL_malloc!("source/acos5_64.d", 2423LU) error instantiating
The proposed PR solves for this one case, though there are more templates using template parameters (string file = __FILE__, size_t line = __LINE__) that woun't compile.
If this PR is accepted, I will follow-up with another PR referring to those.
In another context (one of my bindings) I faced a peculiarity …
=> crypto.d: Fix template OPENSSL_malloc

deimos/openssl/hmac.d
Defined these methods which are defined in openssl 1.1.0h:
HMAC_CTX * HMAC_CTX_new();
void HMAC_CTX_free(HMAC_CTX *ctx);
void HMAC_CTX_reset(HMAC_CTX * ctx);
Removed deprecated methods which result in an unresolved symbol:
void HMAC_CTX_init(HMAC_CTX* ctx);
void HMAC_CTX_cleanup(HMAC_CTX* ctx);
=> Update to openssl 1.1.0h support

deimos/openssl/hmac.d
It was referencing a symbol removed in pull #42
Fixes #43
=> Remove deprecated alias

CONTRIBUTING.md, deimos/openssl/asn1.d, deimos/openssl/conf.d, deimos/openssl/crypto.d, deimos/openssl/ossl_typ.d, deimos/openssl/pem.d, deimos/openssl/safestack.d, deimos/openssl/x509.d, deimos/openssl/x509_vfy.d, deimos/openssl/x509v3.d
See previous discussions in #51. New pull request with fixes from the code-review.
=> Updated x509 modules to match openssl 1.1.0h API, reviewed

deimos/openssl/x509.d
=> deimos.openssl.x509: Add missing public import

.github/workflows/ci.yml
```
While working on the CI, I ended up changing the scheme used for the key,
but as the old scheme had been looked up successfully in my fork,
it didn't break until it landed on master.
```
See L38 for the correct scheme.
=> CI: Use the correct key when looking up OpenSSL

.github/workflows/ci.yml, dub.sdl, source/deimos/openssl/rsa.d
```
rsa: EVP_PKEY_CTX_set_rsa_keygen_* are no longer macros in v3.0.0, add _primes
As noted in the comments, those three functions were changed from macros
to actual function in v3.0.0, and [...]_pubexp was deprecated.
Additionally, the bindings were previously missing the [...]_primes
function, which was a macro in previous version, so it has been added.
```
Let's see what the CI says. Looks like `rsa` needs a lot of love, I am looking into backporting more internal patches...
=> rsa: EVP_PKEY_CTX_set_rsa_keygen_* are no longer macros in v3.0.0

source/deimos/openssl/evp.d, source/deimos/openssl/rsa.d, source/deimos/openssl/types.d
The RSA header is hugely different from what is checked in. Trying to fix this while retaining compatibility with all supported versions is challenging.
=> rsa: `rsa_method_st` and `rsa_st` are opaque since v1.1.0

.github/workflows/ci.yml
Because I'm lazy I don't want to have to do it myself every time :)
=> Add a CI that test against vibe-d:tls

.gitignore, source/deimos/openssl/evp.d, source/deimos/openssl/rsa.d, source/deimos/openssl/ssl.d
~See each commits for details. The bunch of the fixes are focused on EVP, as the high-level interface needs to be made available for users to adapt to it. On the other hand, the `SSL_get_peer_certificate` is probably a common breakage in user code.~
Will submit the EVP fixes separately.
=> Some forward compatible fixes

source/deimos/openssl/bn.d, source/deimos/openssl/buffer.d, source/deimos/openssl/evp.d, source/deimos/openssl/hmac.d, source/deimos/openssl/pem.d, source/deimos/openssl/types.d
Also had to simplify `types` in the process because the amount of circular dependencies tripped the compiler.
=> evp: Add all missing bindings for v1.1.0 and some for later versions

source/deimos/openssl/err.d
Fairly straightforward, didn't cover the full header though.
=> err: Implement basis for new error API

source/deimos/openssl/stack.d
```
This allows people to update to the new v1.1.0 API without
breaking compatibility with v1.0.x.
```
@CyberShadow : For v3.2.0 onwards I would like to deprecate the old names (pre-v1.1.0).
The deprecation will be only on the backwards compatible aliases: In this case, lines 119 through 141.
Benefit is twofold: People are nudged to upgrade (usually in trivial ways), and it makes the binding clearer.
=> Add forward-compatible aliases for stack module

source/deimos/openssl/bio.d, source/deimos/openssl/crypto.d, source/deimos/openssl/dh.d, source/deimos/openssl/dsa.d, source/deimos/openssl/ecdh.d, source/deimos/openssl/ecdsa.d, source/deimos/openssl/engine.d, source/deimos/openssl/rsa.d, source/deimos/openssl/ssl.d, source/deimos/openssl/ui.d, source/deimos/openssl/x509.d, source/deimos/openssl/x509_vfy.d
```
This change happened in v1.1.0 but was not applied to the bindings.
Some macros were introduced post-1.1 and the backward-compatible
definition has been introduced.
```
https://github.com/openssl/openssl/commit/e6390acac925f952cfd06ccdbba0b273b8f71551
Note that the above commit had bugs (see the `SSL_*` functions have their indexes swapped, `SESSION` uses `CTX`, `CTX uses `SSL`, and `SSL` uses `SESSION`...) but that was corrected later it seems.
=> Change *_get_ex_new_index functions to macros

dub.sdl, scripts/generate_version.d
As we see spurious failures (`version_.di` not generated/importable) when calling dub recursively.
The `generate_version` executable is built each time this way, not cached by dub anymore, but it's built pretty quickly (0.5 secs with LDC on my Linux x64 box, 0.3 secs with DMD).
=> Avoid running dub recursively in pre-generate command, call D compiler directly

source/deimos/openssl/kdf.di
Wanted to use OpenSSL v3 but encountered some errors.
```d
../../../.dub/packages/openssl-3.2.1/openssl/source/deimos/openssl/kdf.di(165,4): Error: undefined identifier `pctx`, did you mean variable `ctx`?
source/crypto_ops.d(132,37): Error: template instance `deimos.openssl.kdf.EVP_PKEY_CTX_set_hkdf_md!()` error instantiating
../../../.dub/packages/openssl-3.2.1/openssl/source/deimos/openssl/kdf.di(177,4): Error: undefined identifier `pctx`, did you mean variable `ctx`?
source/crypto_ops.d(135,39): Error: template instance `deimos.openssl.kdf.EVP_PKEY_CTX_set1_hkdf_key!()` error instantiating
../../../.dub/packages/openssl-3.2.1/openssl/source/deimos/openssl/kdf.di(171,4): Error: undefined identifier `pctx`, did you mean variable `ctx`?
source/crypto_ops.d(138,40): Error: template …
```
=> Fix typo and type mismatch in kdf.di

source/deimos/openssl/ecdsa.di
These functions are used in the `hunt-jwt` library. They are already in the outdated `hunt-openssl` fork of this package, but they should be useful over here as well.
=> Add some missing ECDSA_SIG_* functions

source/deimos/openssl/evp.di
`EVP_PKEY_id` and `EVP_PKEY_base_id` were renamed to `EVPK_PKEY_get_id` and `EVP_PKEY_get_base_id` respectively. Compatibility macros were added in openssl, but the linker is unaware of them, causing linker errors in some projects when linking them to openssl3.
https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_id.html#HISTORY
=> Add EVP_PKEY_get_* and aliases for openssl>=3.0

source/deimos/openssl/evp.di
- The functions are renamed to EVP_PKEY_get_bits() and EVP_PKEY_get_size()
- Added new declarations for new names
- Added aliases for old names
=> Changed in 3.0.0: EVP_PKEY_bits() and EVP_PKEY_size()

source/deimos/openssl/evp.di
These two declarations seem to be missing. Needed for ED25519 signing and verify.
=> Add declarations for EVP_DigestSign() and EVP_DigestVerify()

dub.sdl
Allows an upstream package to provide the binaries required for linking. This is especially important for mobile platforms and in certain cross-compilation scenarios.
=> Add a manual-linking configuration

source/deimos/openssl/opensslv.di
@CyberShadow : Not sure how to handle this as I expect it's not compatible with our `.di` approach.
=> Version handling: Handle multiple digits

source/deimos/openssl/opensslv.di
=> deimos.openssl.opensslv: Fix parsing versions with suffixes

source/deimos/openssl/opensslv.di
Work around https://issues.dlang.org/show_bug.cgi?id=24146 ; closes #107.
=> deimos.openssl.opensslv: Remove use of Phobos

dub.sdl
Hello, i tried to use gdc for a project and this library fail to compile because gdc doesn't support -run, so i thought i could "emulate" the run behaviour by compiling/running/deleting the script for target posix-gdc.
Disclaimer:
I tried this modification only to build my own project in fedora 40, so review this and please provide feedback if i need to change something.
=> Support GDC by splitting run in build, execute and cleanup

source/deimos/openssl/ssl.di
Where SSLOptionType is ulong (on all platforms since v3), but c_long is 32-bit (Windows-specific). This fixes compilation errors when using SSL_CTX_set_mode() etc.
=> Add casts from `SSLOptionType` to `c_long`, required with OpenSSL 3+ on Windows
